" vim 配置文件，改名为 .vimrc 后移动到 home 下就可以了

" 
set smarttab

" 设置tab=4空格
set tabstop=4

" 设置换行自动缩进长度为4个空格
set shiftwidth=4

" 设置tab符自动转换为空格
set expandtab

" 设置智能缩进，其他可选缩进方式：autoindent, cindent, indentexpr
set smartindent

" 显示行号
set number

" 高亮搜索
set hlsearch

" 输入搜索内容时就显示搜索结果
set incsearch

" 高亮光标所在行
set cursorline
" 美化 
" cterm 表示为原生vim设置样式，设置为NONE表示可以自定义设置
" ctermbg 设置终端vim的背景色 ctermfg 设置终端vim的前景色
" guibg 和 guifg 分别是设置gvim的背景色和前景色
"
hi CursorLine   cterm=NONE ctermbg=black ctermfg=green guibg=None guifg=None

" 高亮光标所在列
set cursorcolumn
" 美化
hi CursorColumn cterm=NONE ctermbg=black ctermfg=green guibg=None guifg=None

" 永久显示状态栏
set laststatus=2

" 在窗口的最上面显示当前打开文件的路径和文件名
let &titlestring = expand("%:p")
if &term == "screen"
  set t_ts=^[k
  set t_fs=^[\
endif
if &term == "screen" || &term == "xterm"
  set title
endif

" 在状态栏显示路径
set statusline=\ %<%F[%1*%M%*%n%R%H]%=\ %y\ %0(%{&fileformat}\ %{&encoding}\%c:%l/%L%)\

" 直接复制到系统粘贴版
set clipboard=unnamed

"使用 F10 开关 NERDTree
nmap <F10> :NERDTree <CR>

"使用系统粘贴板
set clipboard=unnamed
